### ISSUE TITLE
Vote processed twice

### ISSUE THREAD

**Issue by Matthww** [ProjectInfinity/PocketVote#24]
votes are getting processed twice whenever the player is not logged in while voting.
```
---
dev: false
version: 4
identity: id
secret: sec
lock: true
vote-expiration: 7
multi-server:
  enabled: false
  role: master
  mysql:
    host: 127.0.0.1
    port: 3306
    username: vote
    password: f
    database: Votes
onvote:
  run-cmd: []
  online-cmd:
  - say Â§2The player Â§eÂ§l%playerÂ§r Â§2voted with Â§rÂ§b/voteÂ§r Â§2and got Â§612 diamonds,
    10 obsidian and $5.000!
  - givemoney "%player" 5000
  - give "%player" 264 12
  - give "%player" 49 10
  - give "%player" 364 16
  - key common 4 "%player"
  - key uncommon 1 "%player"
votes:
```
